### ISSUE TITLE
Specify curl

### ISSUE THREAD

**Issue by Jackymancs4** [makeworld-the-better-one/homebrew-tap#1]
In my experience Neither `make` nor `curl` are part of stardard base distributions (definitely not on macOS), and they cannot be assumed to be present.

I suggest adding
```
depends_on "curl" => :build
depends_on "cmake" => :build
```

**Comment by makew0rld** [comment]
I assumed Homebrew already has a dep on curl, you need it to install it for example. Also this project doesn't use cmake, just regular make.

I've added a whole bunch of commits just now and did testing, what I've ended up with is a dependency on `"make"`, which is installed as `gmake`. Let me know if you still have issues.

**Comment by Jackymancs4** [comment]
> I assumed Homebrew already has a dep on curl, you need it to install it for example.

That's technically true (it can fallback to wget if curl is not found). The problem is that both curl or make can be manually removed after homebrew installation, with no repercussion. Adding them as build deps assure that when installing a formula thay are there one way or another.

> Also this project doesn't use cmake, just regular make.

That was a typo on my side. I indeed intended make.

> Let me know if you still have issues.

Nope, seems good.

**Comment by makew0rld** [comment]
Ah ok. The problem is when I had curl as a dep, I got this:

```
curl is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have curl first in your PATH run:
  echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> /Users/<user>/.bash_profile

For compilers to find curl you may need to set:
  export LDFLAGS="-L/usr/local/opt/curl/lib"
  export CPPFLAGS="-I/usr/local/opt/curl/include"


zsh completions have been installed to:
  /usr/local/opt/curl/share/zsh/site-functions
```

So I thought there was no point in installing it if I couldn't even use it. I guess it's useful if they removed curl, maybe homebrew would just link their curl?

**Comment by Jackymancs4** [comment]
Never really used curl as build dep for the reasons of #2 so I'm a little unprepared on the matter. I could come back at you by tomorrow if you like.

**Comment by makew0rld** [comment]
That would be helpful, thanks.
