### ISSUE TITLE
Don't use curl for assets

### ISSUE THREAD

**Issue by Jackymancs4** [makeworld-the-better-one/homebrew-tap#2]
Continuing from https://github.com/makeworld-the-better-one/amfora/issues/63#issuecomment-692913871

the solution of your problem is something along the lines:

```ruby
if not build.head?
	system "curl", "-sSL", "https://github.com/makeworld-the-better-one/amfora/raw/b2b8e30/Makefile", "-o", "Makefile"
end
```

But I suggest you taking a look at the resource block here: https://rubydoc.brew.sh/Formula#resource-class_method

Among the many benefits there is validation and caching.
Using the curl hack (downloading a potentially untrusted extra file in the install block) would never be accepted by the core homebrew.

You could also resort the path block as an alternative.

**Comment by makew0rld** [comment]
This is only a temporary hack until the next version comes out. But I will use this code sample, thank you.

**Comment by makew0rld** [comment]
Added in 588d378.
