### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by Jackymancs4** [makeworld-the-better-one/homebrew-tap#3]
The current test doesn't actually prove that the installation worked (only that an executable is present in the /local/bin folder), because if there was a previous installation `brew test amfora` could still pass.

**Comment by makew0rld** [comment]
Can you provide a code sample that will test for the beginning string `Amfora v1.5.0`? Sorry, I don't know Ruby.

**Comment by Jackymancs4** [comment]
Sure thing. Quoting from my own formula here:
https://github.com/Jackymancs4/homebrew-tap/blob/0be18504d8874f007e4dac8cdcbe6e383fcdee9d/Formula/amfora.rb#L27-L29


```ruby
  test do
    assert_equal shell_output("#{bin}/amfora -v").chomp, "amfora v#{version}"
  end
```

**Comment by makew0rld** [comment]
Added in 631a4c9, thanks!
