### ISSUE TITLE
Install .desktop file

### ISSUE THREAD

**Issue by Jackymancs4** [makeworld-the-better-one/homebrew-tap#4]
Continuing the discussion https://github.com/makeworld-the-better-one/amfora/issues/63#issuecomment-692804367 about installing the .desktop file I still think is a good idea (mainly for the automatic xdg association of gemini uri). If you want to be sure to not install it on macOS you could do something like:

```ruby
  if not OS.mac?
	# do the thing
  end
```

**Comment by makew0rld** [comment]
Added in a9fdd99, I forgot homebrew is used on non-mac OSes. Thanks!
