### ISSUE TITLE
Find in makefile fails 

### ISSUE THREAD

**Issue by Jackymancs4** [makeworld-the-better-one/homebrew-tap#7]
Now that (with #6 ) `!=` operator is evaluated, the build process warns me two times that `find: illegal option -- t` 

The problem is in the makefile here:
https://github.com/makeworld-the-better-one/amfora/blob/fe0fd784bb47ffe885c64baa91f18e50f3a54b96/Makefile#L3-L4

where mac use the BSD version of find which is different from GNUs (for docs: https://stackoverflow.com/questions/25840713/illegal-option-error-when-using-find-on-macos).

Maybe this should be filed on the Amfora repo.

**Comment by makew0rld** [comment]
Fixed in makeworld-the-better-one/amfora@3cb15cb, thanks for reporting! Let me know if you still have any issues.

**Comment by Jackymancs4** [comment]
Great! You may want to update the reference here https://github.com/makeworld-the-better-one/homebrew-tap/blob/0aad8a7bd1726fb325fd2d5f495cb01212fa5f65/Formula/amfora.rb#L27

**Comment by makew0rld** [comment]
Thanks, I meant to! Fixed in 8d9aab7.
